export const ACTION_TYPES = {
  SET_VIDEOS: 'SET_VIDEOS',
  SET_SIDEBAR: 'SET_SIDEBAR',
  SET_SELECTED_CATEGORY: 'SET_SELECTED_CATEGORY',
  SET_VIDEO_ID: 'SET_VIDEO_ID',
  SET_VIDEO_DETAILS: 'SET_VIDEO_DETAILS'
}
